<a href="https://colab.research.google.com/github/TonmoyTalukder/Bangla-Key2Text/blob/main/Bangla-Key2Text/Bengali_Key2Text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pre-Processing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
# df =  pd.read_csv('/content/drive/MyDrive/TrainingT5/BanSen/BanSen568270.csv')
# df =  pd.read_csv('/content/drive/MyDrive/Shibli Sir/Multi-Modal Research Team/Work 0: Keywords to Text in Bengali/DataV3/strkeysDfV01.csv')
# df =  pd.read_csv('/content/drive/MyDrive/BengaliKey2Text/DataV3/strkeysDfVOld.csv')
df =  pd.read_csv('/content/drive/MyDrive/BengaliKey2Text/DataV3/strkeysDfV01.csv')
# df = df.head(100000)
# df = df.iloc[400000:500000]
# df = df.tail(91750)
df

,bn_Keywords,bn_Sentence
0,প্রতিযোগিতায় বড় ফেডারেশনের দেওয়া মধ্যে কি বড় ল...,"এ কারণে এসএ গেমস, এশিয়ান কিংবা অলিম্পিক গেমসের..."
1,আকার পাটুরিয়াদৌলতদিয়া আরিচানগরবাড়ী লঞ্চঘাটের ক...,"পর্যায়ক্রমে পাটুরিয়া-দৌলতদিয়া, আরিচা-নগরবাড়ী, ..."
2,কেনেন ৫৪ টাকায় শতক,গাজর-টমেটো বিক্রির টাকায় কেনেন ৫৪ শতক জমি।
3,ঘোষণা রাখে মধ্যে যৌক্তিক ওয়েজ বোর্ড এর বিশ্লে...,"এর মধ্যে নবম ওয়েজ বোর্ড ঘোষণা কতটুকু যৌক্তিক,..."
4,এক লাবণ্যতা সমস্ত মাদকতা ও কিছুতে,কী এক ভিন্ন মাদকতা ও লাবণ্যতা তার সমস্ত কিছুতে!
...,...,...
3070491,১০কুইন্টন ৪০২তিলকরত্নে ১৫দিনেশ রানমার্টিন টেলর...,সর্বোচ্চ রান নাম ম্যাচ ...
3070492,ভঙ্গি দেখে বসার পারলাম,বসার ভঙ্গি দেখে চিনতে পারলাম।
3070493,হতাশা এই করেন ভাড়া ওই,এই হতাশা কাটাতে নিশিমোতোকে ভাড়া করেন ওই শিক...
3070494,প্রসারিত ভাবত বছরে বিলিয়ন এক সেপিয়ানরা হবে,"সেপিয়ানরা ভাবত, সূর্য এক বিলিয়ন বছরে ১০ শতাংশ ..."
3070495,রবি ও বুধবার দিন,গুরুত্বপূর্ণ দিন রবি ও বুধবার।

In [ ]:
df.columns = ["keywords", "text"]
# df = df.head(400000)
# df = df.iloc[1200000:1579900]
# df = df.iloc[1579900:2000000]
# df = df.iloc[2000000:2400000]
df = df.iloc[2400000:2800000]
df = df.reset_index(drop=True)
df

In [ ]:
df

,keywords,text
0,ওই বাড়িতে ক্ষুব্ধ অগ্নিসংযোগ,একপর্যায়ে ক্ষুব্ধ লোকজন ওই বাড়িতে অগ্নিসংযোগ ক...
1,কাটে এমনভাবেই আমার,আমার ঈদগুলো এমনভাবেই কাটে।
2,শারীরিক উঠেছে মুঠোফোন চুরির নির্যাতনের অপরাধে ...,সেখানে কথিত মুঠোফোন চুরির অপরাধে এক কিশোরকে (১...
3,জানেন সম্পর্কে না কম হয়েছে আলোচকেরা শিল্পী অনু...,"অনুষ্ঠানে দর্শক কম হয়েছে, আলোচকেরা বাচ্চু সম্প..."
4,করছি যন্ত্রণা ও এ শক্তি পথ নেবে নতুন আবার শিক্...,"আশা করছি, এ ঘটনা থেকে যন্ত্রণা ও শোকের অংশটুকু..."
...,...,...
399995,উল্লেখ করেন জবাবে প্রতিমন্ত্রী বিভিন্ন পদক্ষেপ...,জবাবে প্রতিমন্ত্রী পাটজাত পণ্যের উন্নয়নে সরকার...
399996,সংগঠন আয়োজন গণিত করা ফোরাম শিক্ষকদের শিক্ষাবিষ...,অনেক আয়োজন করে খুলনা বিভাগের গণিত শিক্ষকদের নি...
399997,সঠিক কাজি১৮ ছাপা হলো,সঠিক উত্তর ছাপা হলো নিচের অংশে।কিশোর কাজি১৮।
399998,এসেছে যায় আমাদের আজকে তার বাসায়,"তার খাতাতে পাওয়া যায়, ‘শুভ্র আজকে আমাদের বাস..."
399999,সাফল্য অধ্যায় বার্সা ভরাই,গার্দিওলা-এনরিকের বার্সা অধ্যায় সাফল্য ভরাই।

In [ ]:
print(df.isnull().sum())

keywords    0
text        0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
print(df.isnull().sum())

keywords    0
text        0
dtype: int64

## Fine Tuning : T5

### Install

In [ ]:
!pip install --upgrade pip
!pip install --no-cache-dir sentencepiece
!pip install --upgrade git+https://github.com/huggingface/transformers
!pip install --upgrade pytorch_lightning

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sentencepiece
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.5 MB/s eta 0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.99
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-ds43si5r
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-ds43si5r
  Resolved https://github.com/huggingface/transformers to commit 8f093fb799246f7dd9104ff44728da0c53a9f67a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (3.12.0)
Collecting huggingface-hub<1.0,>=0.14.1 (from transformers==4.31.0.dev0)
  Downloading huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 15.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (2.27.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers==4.31.0.dev0)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 123.1 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers==4.31.0.dev0)
  Downloading safetensors-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 87.0 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.31.0.dev0) (4.65.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.31.0.dev0) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.31.0.dev0) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.31.0.dev0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.31.0.dev0) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.31.0.dev0) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.31.0.dev0) (3.4)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.31.0.dev0-py3-none-any.whl size=7170473 sha256=92e87d4fe297870e90acad690e4bae5519070abd63c5f9c5df8e1db1992a88d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-fwbsmxtu/wheels/c0/14/d6/6c9a5582d2ac191ec0a483be151a4495fe1eb2a6706ca49f1b
Successfully built transformers
Installing collected packages: tokenizers, safetensors, huggingface-hub, transformers
Successfully installed huggingface-hub-0.15.1 safetensors-0.3.1 tokenizers-0.13.3 transformers-4.31.0.dev0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pytorch_lightning
  Downloading pytorch_lightning-2.0.3-py3-none-any.whl (720 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 720.6/720.6 kB 25.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (1.22.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (2.0.1+cu118)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (4.65.0)
Requirement already satisfied: PyYAML>=5.4 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (6.0)
Requirement already satisfied: fsspec[http]>2021.06.0 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (2023.4.0)
Collecting torchmetrics>=0.7.0 (from pytorch_lightning)
  Downloading torchmetrics-0.11.4-py3-none-any.whl (519 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.2/519.2 kB 54.3 MB/s eta 0:00:00
Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (23.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from pytorch_lightning) (4.5.0)
Collecting lightning-utilities>=0.7.0 (from pytorch_lightning)
  Downloading lightning_utilities-0.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>2021.06.0->pytorch_lightning) (2.27.1)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 75.5 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->pytorch_lightning) (3.12.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->pytorch_lightning) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->pytorch_lightning) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->pytorch_lightning) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->pytorch_lightning) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->pytorch_lightning) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->pytorch_lightning) (16.0.5)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (2.0.12)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 15.9 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 35.9 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 19.4 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->pytorch_lightning) (2.1.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->fsspec[http]>2021.06.0->pytorch_lightning) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->fsspec[http]>2021.06.0->pytorch_lightning) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->fsspec[http]>2021.06.0->pytorch_lightning) (3.4)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->pytorch_lightning) (1.3.0)
Installing collected packages: multidict, lightning-utilities, frozenlist, async-timeout, yarl, aiosignal, aiohttp, torchmetrics, pytorch_lightning
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 frozenlist-1.3.3 lightning-utilities-0.8.0 multidict-6.0.4 pytorch_lightning-2.0.3 torchmetrics-0.11.4 yarl-1.9.2

In [ ]:
!pip install rouge_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge_score) (3.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.22.4)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score) (4.65.0)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=f0ca827c7f918daab7d9ba741c2d43cc91bec31f9b412db5c5322672f658f624
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
!pip install datasets
from datasets import load_metric

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting datasets
  Downloading datasets-2.12.0-py3-none-any.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 35.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.22.4)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (9.0.0)
Collecting dill<0.3.7,>=0.3.0 (from datasets)
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 16.2 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.27.1)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.65.0)
Collecting xxhash (from datasets)
  Downloading xxhash-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 28.9 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.14-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 18.4 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.4.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.8.4)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.15.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (23.1)
Collecting responses<0.19 (from datasets)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, dill, responses, multiprocess, datasets
Successfully installed datasets-2.12.0 dill-0.3.6 multiprocess-0.70.14 responses-0.18.0 xxhash-3.2.0

### Import

In [ ]:
from os import access
import shutil

import torch
import numpy as np
import pandas as pd
# from datasets import load_metric
from tqdm.auto import tqdm
from transformers import (
    AdamW,
    T5ForConditionalGeneration,
    T5TokenizerFast as T5Tokenizer,
    AutoTokenizer,
    AutoModelWithLMHead
)
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl
# from pytorch_lightning.loggers import WandbLogger
from pytorch_lightning.callbacks.early_stopping import EarlyStopping
from pytorch_lightning import LightningDataModule
from pytorch_lightning import Trainer
from getpass import getpass
from huggingface_hub import HfApi, Repository
from pathlib import Path

from sklearn.model_selection import train_test_split

from transformers import MBartForConditionalGeneration, AutoTokenizer, AlbertTokenizer, AutoModelForSeq2SeqLM

### Functions

In [ ]:
# def cleanDataX(keywords):

#   strs = ''
#   Flag = 0

#   for i in range(len(keywords)):

#     if keywords[i] == '[':
#       Flag = 0
#       continue

#     elif keywords[i] ==']':
#       Flag = 0
#       continue

#     elif keywords[i] == chr(39): # '
#       Flag = 0
#       continue

#     elif keywords[i] == chr(44): # ,
#       Flag = 0
#       continue

#     # elif keywords[i] == chr(32) and Flag == 0: # Space
#     #   Flag = 1

#     # elif keywords[i] == chr(32) and Flag == 1: # Space
#     #   Flag = 0
#     #   continue

#     else:
#       Flag = 0
#       strs = strs + keywords[i]

#   return ''.join((x for x in strs if not x.isdigit()))

# def cleanDataY(text):

#   return ''.join((x for x in text if not x.isdigit()))


import sys
print(sys.getrecursionlimit())
sys.setrecursionlimit(8200)
print(sys.getrecursionlimit())

!pip install rouge

from rouge import Rouge


def rougeScore(columnName1, columnName2):

    newDf = test_df.filter([columnName1, columnName2], axis=1)

    # newDf[columnName1] = newDf[columnName1].apply(cleanDataX)
    # newDf[columnName2] = newDf[columnName2].apply(cleanDataY)

    newDf =  newDf.reset_index()
    newDf = newDf.head(1000)

    lenS = newDf.shape[0]

    rscore1r = 0
    rscore1p = 0
    rscore1f = 0
    rscore2r = 0
    rscore2p = 0
    rscore2f = 0
    rscorelr = 0
    rscorelp = 0
    rscorelf = 0
    rouge = Rouge()

    for i in range(lenS):

        score = rouge.get_scores(model.predict([newDf[columnName1][i]]), newDf[columnName2][i])

        rscore1r = rscore1r + score[0]['rouge-1']['r']
        rscore1p = rscore1p + score[0]['rouge-1']['p']
        rscore1f = rscore1f + score[0]['rouge-1']['f']

        rscore2r = rscore2r + score[0]['rouge-2']['r']
        rscore2p = rscore2p + score[0]['rouge-2']['p']
        rscore2f = rscore2f + score[0]['rouge-2']['f']

        rscorelr = rscorelr + score[0]['rouge-l']['r']
        rscorelp = rscorelp + score[0]['rouge-l']['p']
        rscorelf = rscorelf + score[0]['rouge-l']['f']

        rscore = {'rouge-1': {'r': rscore1r/lenS,
                            'p': rscore1p/lenS,
                            'f': rscore1f/lenS},
                  'rouge-2': {'r': rscore2r/lenS,
                            'p': rscore2p/lenS,
                            'f': rscore2f/lenS},
                  'rouge-l': {'r': rscorelr/lenS,
                            'p': rscorelp/lenS,
                            'f': rscorelf/lenS}}

    return rscore

1000
8200
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from rouge) (1.16.0)
Installing collected packages: rouge
Successfully installed rouge-1.0.1

In [ ]:
torch.cuda.empty_cache()
pl.seed_everything(42)


class DataModule(Dataset):
    """
    Data Module for pytorch
    """

    def __init__(
        self,
        data: pd.DataFrame,
        tokenizer: AutoTokenizer,
        source_max_token_len: int = 64,
        target_max_token_len: int = 64,
    ):
        """
        :param data:
        :param tokenizer:
        :param source_max_token_len:
        :param target_max_token_len:
        """
        self.data = data
        self.target_max_token_len = target_max_token_len
        self.source_max_token_len = source_max_token_len
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index: int):
        data_row = self.data.iloc[index]

        keywords_encoding = self.tokenizer(
            data_row["keywords"],
            max_length=self.source_max_token_len,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            add_special_tokens=True,
            return_tensors="pt",
        )

        text_encoding = self.tokenizer(
            data_row["text"],
            max_length=self.target_max_token_len,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            add_special_tokens=True,
            return_tensors="pt",
        )

        labels = text_encoding["input_ids"]
        labels[labels == 0] = -100

        return dict(
            keywords=data_row["keywords"],
            text=data_row["text"],
            keywords_input_ids=keywords_encoding["input_ids"].flatten(),
            keywords_attention_mask=keywords_encoding["attention_mask"].flatten(),
            labels=labels.flatten(),
            labels_attention_mask=text_encoding["attention_mask"].flatten(),
        )


class PLDataModule(LightningDataModule):
    def __init__(
        self,
        train_df: pd.DataFrame,
        test_df: pd.DataFrame,
        tokenizer: AutoTokenizer,
        source_max_token_len: int = 64,
        target_max_token_len: int = 64,
        batch_size: int = 4,
        split: float = 0.1,
    ):
        """
        :param data_df:
        :param tokenizer:
        :param source_max_token_len:
        :param target_max_token_len:
        :param batch_size:
        :param split:
        """
        super().__init__()
        self.train_df = train_df
        self.test_df = test_df
        self.split = split
        self.batch_size = batch_size
        self.target_max_token_len = target_max_token_len
        self.source_max_token_len = source_max_token_len
        self.tokenizer = tokenizer

    def setup(self, stage=None):
        self.train_dataset = DataModule(
            self.train_df,
            self.tokenizer,
            self.source_max_token_len,
            self.target_max_token_len,
        )
        self.test_dataset = DataModule(
            self.test_df,
            self.tokenizer,
            self.source_max_token_len,
            self.target_max_token_len,
        )

    def train_dataloader(self):
        """training dataloader"""
        return DataLoader(
            self.train_dataset, batch_size=self.batch_size, shuffle=True, num_workers=2
        )

    def test_dataloader(self):
        """test dataloader"""
        return DataLoader(
            self.test_dataset, batch_size=self.batch_size, shuffle=False, num_workers=2
        )

    def val_dataloader(self):
        """validation dataloader"""
        return DataLoader(
            self.test_dataset, batch_size=self.batch_size, shuffle=False, num_workers=2
        )


class LightningModel(pl.LightningModule):
    """PyTorch Lightning Model class"""

    def __init__(self, tokenizer, model, output: str = "outputs"):
        """
        initiates a PyTorch Lightning Model
        Args:
            tokenizer : T5 tokenizer
            model : T5 model
            output (str, optional): output directory to save model checkpoints. Defaults to "outputs".
        """
        super().__init__()
        self.model = model
        self.tokenizer = tokenizer
        self.output = output
        # self.val_acc = Accuracy()
        # self.train_acc = Accuracy()

    def forward(self, input_ids, attention_mask, decoder_attention_mask, labels=None):
        """forward step"""
        output = self.model(
            input_ids,
            attention_mask=attention_mask,
            labels=labels,
            decoder_attention_mask=decoder_attention_mask,
        )

        return output.loss, output.logits

    def training_step(self, batch, batch_size):
        """training step"""
        input_ids = batch["keywords_input_ids"]
        attention_mask = batch["keywords_attention_mask"]
        labels = batch["labels"]
        labels_attention_mask = batch["labels_attention_mask"]

        loss, outputs = self(
            input_ids=input_ids,
            attention_mask=attention_mask,
            decoder_attention_mask=labels_attention_mask,
            labels=labels,
        )
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_size):
        """validation step"""
        input_ids = batch["keywords_input_ids"]
        attention_mask = batch["keywords_attention_mask"]
        labels = batch["labels"]
        labels_attention_mask = batch["labels_attention_mask"]

        loss, outputs = self(
            input_ids=input_ids,
            attention_mask=attention_mask,
            decoder_attention_mask=labels_attention_mask,
            labels=labels,
        )
        self.log("val_loss", loss, prog_bar=True)
        return loss

    def test_step(self, batch, batch_size):
        """test step"""
        input_ids = batch["keywords_input_ids"]
        attention_mask = batch["keywords_attention_mask"]
        labels = batch["labels"]
        labels_attention_mask = batch["labels_attention_mask"]

        loss, outputs = self(
            input_ids=input_ids,
            attention_mask=attention_mask,
            decoder_attention_mask=labels_attention_mask,
            labels=labels,
        )

        self.log("test_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        """configure optimizers"""
        return AdamW(self.parameters(), lr=0.0001)


class trainer:
    """
    Keytotext model trainer
    """

    def __init__(self):
        pass

    def from_pretrained(self, model_name="t5-base"):
        """
        Download Model from HF hub
        :param model_name: T5
        :return: Download the model and tokenizer
        """
        self.tokenizer = AutoTokenizer.from_pretrained(f"{model_name}", use_fast=False)
        # self.model = AutoModelWithLMHead.from_pretrained(
        #     f"{model_name}", return_dict=True
        # )
        self.model = AutoModelForSeq2SeqLM.from_pretrained(
            f"{model_name}", return_dict=True, is_trainable=True
        )

    def train(
        self,
        train_df: pd.DataFrame,
        test_df: pd.DataFrame,
        source_max_token_len: int = 64,
        target_max_token_len: int = 64,
        batch_size: int = 8,
        max_epochs: int = 5,
        use_gpu: bool = True,
        outputdir: str = "outputs",
        early_stopping_patience_epochs: int = 0,  # 0 to disable early stopping feature
        test_split=0.1,
        tpu_cores = None,
    ):
        """
        trains T5 model on custom dataset
        Args:
            data_df (pd.DataFrame): training datarame. Dataframe must have 2 column --> "keywords" and "text"
            source_max_token_len (int, optional): max token length of source text. Defaults to 512.
            target_max_token_len (int, optional): max token length of target text. Defaults to 512.
            batch_size (int, optional): batch size. Defaults to 8.
            max_epochs (int, optional): max number of epochs. Defaults to 5.
            use_gpu (bool, optional): if True, model uses gpu for training. Defaults to True.
            outputdir (str, optional): output directory to save model checkpoints. Defaults to "outputs".
            early_stopping_patience_epochs (int, optional): monitors val_loss on epoch end and stops training,
             if val_loss does not improve after the specied number of epochs. set 0 to disable early stopping.
             Defaults to 0 (disabled)
            :param test_df:
            :param train_df:
        """
        self.target_max_token_len = target_max_token_len
        self.max_epoch = max_epochs
        self.train_df = train_df
        self.test_df = test_df

        self.data_module = PLDataModule(
            train_df=train_df,
            test_df=test_df,
            tokenizer=self.tokenizer,
            batch_size=batch_size,
            source_max_token_len=source_max_token_len,
            target_max_token_len=target_max_token_len,
            split=test_split,
        )

        # for param in self.model.parameters():
        #     param.requires_grad = True

        self.T5Model = LightningModel(
            tokenizer=self.tokenizer, model=self.model, output=outputdir
        )
        self.T5Model = self.T5Model.to(self.device)

        # logger = WandbLogger(project="keytotext")

        early_stop_callback = (
            [
                EarlyStopping(
                    monitor="val_loss",
                    min_delta=0.00,
                    patience=early_stopping_patience_epochs,
                    verbose=True,
                    mode="min",
                )
            ]
            if early_stopping_patience_epochs > 0
            else None
        )

        # gpus = -1 if use_gpu else 0
        # if use_gpu == True:
        #   gpus = -1
        # else: gpus = 0

        trainer = Trainer(
            # logger=logger,
            callbacks=early_stop_callback,
            max_epochs=max_epochs,
            # gpus=gpus,
            accelerator="auto", devices="auto", strategy="auto",
            detect_anomaly=True
            # progress_bar_refresh_rate=5,
            # tpu_cores=tpu_cores
        )

        trainer.fit(self.T5Model, self.data_module)
        # self.evaluate(self, test_df, "rouge")

    def load_model(self, model_dir: str = "outputs", use_gpu: bool = False):
        """
        loads a checkpoint for inferencing/prediction
        Args:
            model_dir (str, optional): path to model directory. Defaults to "outputs".
            use_gpu (bool, optional): if True, model uses gpu for inferencing/prediction. Defaults to True.
        """
        # self.model = AutoModelWithLMHead.from_pretrained(f"{model_dir}")
        self.model = AutoModelForSeq2SeqLM.from_pretrained(f"{model_dir}", return_dict=True)
        self.tokenizer = AutoTokenizer.from_pretrained(f"{model_dir}", use_fast=False)
        self.model.enable_input_require_grads()

        if use_gpu:
            if torch.cuda.is_available():
                self.device = torch.device("cuda")
            else:
                raise Exception(
                    "exception ---> no gpu found. set use_gpu=False, to use CPU"
                )
        else:
            self.device = torch.device("cpu")

        self.model = self.model.to(self.device)

    def save_model(self, model_dir="model"):
        """
        Save model to dir
        :param model_dir:
        :return: model is saved
        """
        path = f"{model_dir}"
        self.tokenizer.save_pretrained(path)
        self.model.save_pretrained(path)

    def predict(
        self,
        keywords: list,
        max_length: int = 512,
        num_return_sequences: int = 1,
        num_beams: int = 2,
        top_k: int = 50,
        top_p: float = 0.95,
        do_sample: bool = True,
        repetition_penalty: float = 2.5,
        length_penalty: float = 1.0,
        early_stopping: bool = True,
        skip_special_tokens: bool = True,
        clean_up_tokenization_spaces: bool = True,
        use_gpu: bool = True,
    ):
        """
        generates prediction for K2T model
        Args:
            Keywords (list): any keywords for generating predictions
            max_length (int, optional): max token length of prediction. Defaults to 512.
            num_return_sequences (int, optional): number of predictions to be returned. Defaults to 1.
            num_beams (int, optional): number of beams. Defaults to 2.
            top_k (int, optional): Defaults to 50.
            top_p (float, optional): Defaults to 0.95.
            do_sample (bool, optional): Defaults to True.
            repetition_penalty (float, optional): Defaults to 2.5.
            length_penalty (float, optional): Defaults to 1.0.
            early_stopping (bool, optional): Defaults to True.
            skip_special_tokens (bool, optional): Defaults to True.
            clean_up_tokenization_spaces (bool, optional): Defaults to True.
            use_gpu: Defaults to True.
        Returns:
            str: returns predictions
        """
        if use_gpu:
            if torch.cuda.is_available():
                self.device = torch.device("cuda")
            else:
                raise Exception(
                    "exception ---> no gpu found. set use_gpu=False, to use CPU"
                )
        else:
            self.device = torch.device("cpu")

        source_text = " ".join(map(str, keywords))

        input_ids = self.tokenizer.encode(
            source_text, return_tensors="pt", add_special_tokens=True
        )

        input_ids = input_ids.to(self.device)
        generated_ids = self.model.generate(
            input_ids=input_ids,
            num_beams=num_beams,
            max_length=max_length,
            repetition_penalty=repetition_penalty,
            length_penalty=length_penalty,
            early_stopping=early_stopping,
            top_p=top_p,
            top_k=top_k,
            num_return_sequences=num_return_sequences,
        )
        preds = [
            self.tokenizer.decode(
                g,
                skip_special_tokens=skip_special_tokens,
                clean_up_tokenization_spaces=clean_up_tokenization_spaces,
            )
            for g in generated_ids
        ]
        return preds[0]

    def evaluate(self, test_df: pd.DataFrame, metrics: str = "rouge"):
        """
        :param test_df:
        :param metrics:
        :return: Output metrics for keytotext
        """
        metric = load_metric(metrics)
        # input_text = test_df["input_text"]
        input_text = test_df["keywords"]
        # references = test_df["output_text"]
        references = test_df["text"]
        predictions = [self.predict(x) for x in input_text]

        results = metric.compute(predictions=predictions, references=references)

        output = {
            "Rouge 1": {
                "Rouge_1 Low Precision": results["rouge1"].low.precision,
                "Rouge_1 Low recall": results["rouge1"].low.recall,
                "Rouge_1 Low F1": results["rouge1"].low.fmeasure,
                "Rouge_1 Mid Precision": results["rouge1"].mid.precision,
                "Rouge_1 Mid recall": results["rouge1"].mid.recall,
                "Rouge_1 Mid F1": results["rouge1"].mid.fmeasure,
                "Rouge_1 High Precision": results["rouge1"].high.precision,
                "Rouge_1 High recall": results["rouge1"].high.recall,
                "Rouge_1 High F1": results["rouge1"].high.fmeasure,
            },
            "Rouge 2": {
                "Rouge_2 Low Precision": results["rouge2"].low.precision,
                "Rouge_2 Low recall": results["rouge2"].low.recall,
                "Rouge_2 Low F1": results["rouge2"].low.fmeasure,
                "Rouge_2 Mid Precision": results["rouge2"].mid.precision,
                "Rouge_2 Mid recall": results["rouge2"].mid.recall,
                "Rouge_2 Mid F1": results["rouge2"].mid.fmeasure,
                "Rouge_2 High Precision": results["rouge2"].high.precision,
                "Rouge_2 High recall": results["rouge2"].high.recall,
                "Rouge_2 High F1": results["rouge2"].high.fmeasure,
            },
            "Rouge L": {
                "Rouge_L Low Precision": results["rougeL"].low.precision,
                "Rouge_L Low recall": results["rougeL"].low.recall,
                "Rouge_L Low F1": results["rougeL"].low.fmeasure,
                "Rouge_L Mid Precision": results["rougeL"].mid.precision,
                "Rouge_L Mid recall": results["rougeL"].mid.recall,
                "Rouge_L Mid F1": results["rougeL"].mid.fmeasure,
                "Rouge_L High Precision": results["rougeL"].high.precision,
                "Rouge_L High recall": results["rougeL"].high.recall,
                "Rouge_L High F1": results["rougeL"].high.fmeasure,
            },
            "rougeLsum": {
                "rougeLsum Low Precision": results["rougeLsum"].low.precision,
                "rougeLsum Low recall": results["rougeLsum"].low.recall,
                "rougeLsum Low F1": results["rougeLsum"].low.fmeasure,
                "rougeLsum Mid Precision": results["rougeLsum"].mid.precision,
                "rougeLsum Mid recall": results["rougeLsum"].mid.recall,
                "rougeLsum Mid F1": results["rougeLsum"].mid.fmeasure,
                "rougeLsum High Precision": results["rougeLsum"].high.precision,
                "rougeLsum High recall": results["rougeLsum"].high.recall,
                "rougeLsum High F1": results["rougeLsum"].high.fmeasure,
            },
        }
        return output

    def upload(self, hf_username, model_name, token):
        if token is None:
            token = getpass("Enter your HuggingFace access token")
        if Path("./model").exists():
            shutil.rmtree("./model")
        HfApi.set_access_token(token)
        model_url = HfApi().create_repo(token=token, name=model_name, exist_ok=True)
        model_repo = Repository(
            "./model",
            clone_from=model_url,
            use_auth_token=token,
            git_email=f"{hf_username}@users.noreply.huggingface.co",
            git_user=hf_username,
        )

        readme_txt = f"""
        ---
language: "en"
thumbnail: "Keywords to Sentences"
tags:
- keytotext
- k2t
- Keywords to Sentences
model-index:
- name: {model_name}
---
Idea is to build a model which will take keywords as inputs and generate sentences as outputs.
Potential use case can include:
- Marketing
- Search Engine Optimization
- Topic generation etc.
- Fine tuning of topic modeling models
        """.strip()

        (Path(model_repo.local_dir) / "README.md").write_text(readme_txt)
        self.save_model()
        commit_url = model_repo.push_to_hub()

        print("Check out your model at:")
        print(f"https://huggingface.co/{hf_username}/{model_name}")

INFO:lightning_fabric.utilities.seed:Global seed set to 42

### Train Test Splitting

In [ ]:
train_df, test_df = train_test_split(df, test_size=0.2)
train_df.shape, test_df.shape

((320000, 2), (80000, 2))

### Model Training

#### Epoch 1

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV7", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV6", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV5", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV4", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV3", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV2", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model = trainer()
model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV1", use_gpu=True)
# model.from_pretrained(model_name="csebuetnlp/banglat5")
# model.from_pretrained(model_name="csebuetnlp/mT5_multilingual_XLSum")
model.train(train_df=train_df, test_df=test_df, batch_size=8, max_epochs=1,use_gpu=True)
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

In [ ]:
model.save_model(model_dir='/content/drive/MyDrive/BengaliKey2Text/ModelV10')

## Performance Measure

In [ ]:
# model = trainer()
# model.load_model("/content/drive/MyDrive/BengaliKey2Text/ModelV3", use_gpu=True)
# # model.evaluate(test_df, "rouge")
# rougeScore('keywords', 'text')